---
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2

    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache

    - run: mkdir -p ${HOME}/data

    - run:
        name: 'Get test data: ds114_test1'
        command: |
          if [[ ! -d ~/data/ds114_test1 ]]; then
            wget -c -O ${HOME}/ds114_test1.tar "https://osf.io/download/zerfq/" && \
            mkdir -p ${HOME}/data && \
            tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data;
          fi
    - run:
        name: Build Docker image
        command: |
          if [[ -e ~/docker/image.tar ]]; \
            then docker load -i ~/docker/image.tar;
          fi
          git describe --tags --always > version
          docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          mkdir -p ${HOME}/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar

    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data

    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      participant:
        type: string

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run: mkdir -p ${HOME}/outputs

    - run:
        name: print version
        command: |
          docker run -ti --rm --read-only bids/${CIRCLE_PROJECT_REPONAME,,} --version

    - run:
        name: participant << parameters.participant >> for level tests for single session dataset
        command: |
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant \
                --participant_label << parameters.participant >> \
                --stage brain_extraction
        no_output_timeout: 6h

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run:
        name: push to dockerhub
        command: |
          if [[ -n "$DOCKER_PASS" ]]; then
            repo_name=`echo  ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]'`
            echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
            echo "Pushing to DockerHub bids/${repo_name}:unstable"
            docker tag bids/${repo_name} bids/${repo_name}:unstable
            docker push bids/${repo_name}:unstable
            if [[ -n "${CIRCLE_TAG}" ]]; then
              echo "Pushing to DockerHub bids/${repo_name}:${CIRCLE_TAG}"
              docker push bids/${repo_name}:latest
              docker tag bids/${repo_name} bids/${repo_name}:${CIRCLE_TAG}
              docker push bids/${repo_name}:${CIRCLE_TAG};
            fi
          fi

workflows:
  build-test-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
        matrix:
          parameters:
            participant: ['01', '02']
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/

# VS Code Extension Version: 1.5.1
